In [1]:
import pandas as pd

In [2]:
# 평균값
# DataFrame객체.mean()
# DataFrame객체["열 이름"].mean()

df = pd.read_csv("./data/auto-mpg.csv", header=None)
df.columns = ["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model year", "origin", "name"]

df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [4]:
# df.mean() # 숫자가 아닌 열이있으면 에러가뜸.
df.mean(numeric_only=True)

mpg               23.514573
cylinders          5.454774
displacement     193.425879
weight          2970.424623
acceleration      15.568090
model year        76.010050
origin             1.572864
dtype: float64

In [ ]:
df["mpg"].mean()

np.float64(23.51)

In [8]:
# 중앙값
# DataFrame객체.median()
# DataFrame객체["열 이름"].median()

df.median(numeric_only=True)
df.mpg.median()

np.float64(23.0)

In [ ]:
df.max(numeric_only=True)

mpg               46.6
cylinders          8.0
displacement     455.0
weight          5140.0
acceleration      24.8
model year        82.0
origin             3.0
dtype: float64

In [13]:
df.std(numeric_only=True)

mpg               7.815984
cylinders         1.701004
displacement    104.269838
weight          846.841774
acceleration      2.757689
model year        3.697627
origin            0.802055
dtype: float64

In [16]:
# 상관계수
# DataFrame객체.corr()
# DataFrame객체["열 이름의 리스트"].corr()

df[["mpg", "weight"]].corr()

             mpg    weight
mpg     1.000000 -0.831741
weight -0.831741  1.000000