In [1]:
import pandas as pd
import numpy as np

In [15]:
ser = pd.Series(["Apple_사과", "Banana_바나나", "Cherry_체리", np.nan],
                index = ["First ", " Second", " Third", "Fourth"])

In [4]:
result1 = ser.str.split("_")
result1

First       [Apple, 사과]
Second    [Banana, 바나나]
Third      [Cherry, 체리]
Fourth              NaN
dtype: object

In [6]:
result2 = ser.str.split("_", expand=True)
result2

             0    1
First    Apple   사과
Second  Banana  바나나
Third   Cherry   체리
Fourth     NaN  NaN

In [9]:
ser.str.split("_").str.get(1)

First      사과
Second    바나나
Third      체리
Fourth    NaN
dtype: object

In [16]:
# 문자열 메서드

idx = ser.index

print(idx)
print(idx.str.strip())

Index(['First ', ' Second', ' Third', 'Fourth'], dtype='str')
Index(['First', 'Second', 'Third', 'Fourth'], dtype='str')

In [17]:
print(ser.str.replace("_", ":", regex=False))

First        Apple:사과
 Second    Banana:바나나
 Third      Cherry:체리
Fourth            NaN
dtype: str

In [19]:
print(ser.str.replace(r"[^a-zA-Z\s]", "", regex=True))

First       Apple
 Second    Banana
 Third     Cherry
Fourth        NaN
dtype: str

In [20]:
print(ser.str[0])

First        A
 Second      B
 Third       C
Fourth     NaN
dtype: str

In [21]:
print(ser.str[0:4])

First      Appl
 Second    Bana
 Third     Cher
Fourth      NaN
dtype: str

In [22]:
ser.str.contains("A", na=False)

First       True
 Second    False
 Third     False
Fourth     False
dtype: bool

In [25]:
ser.str.contains(r"[A|B][a-z]+")

First       True
 Second     True
 Third     False
Fourth     False
dtype: bool

In [26]:
ser.str.fullmatch(r"[A|B][a-z]+")

First      False
 Second    False
 Third     False
Fourth     False
dtype: bool

In [27]:
ser3 = pd.Series(["a1", "b2", "c3", "d4a5", "e6e7", "f8"], dtype="string")
ser3

0      a1
1      b2
2      c3
3    d4a5
4    e6e7
5      f8
dtype: string

In [28]:
ser3.str.extractall(r"(\d)").groupby(level=0).agg("".join)

    0
0   1
1   2
2   3
3  45
4  67
5   8

In [30]:
ser3.str.extractall(r"([a-z])").groupby(level=0).agg("".join)

    0
0   a
1   b
2   c
3  da
4  ee
5   f

In [31]:
# 숫자랑 필드랑 컬럼으로 분리

ser3.str.extract(r"(?P<Letter>[a-z]+)(?P<Digit>\d+)")

  Letter Digit
0      a     1
1      b     2
2      c     3
3      d     4
4      e     6
5      f     8